info:
  contact: {}
  description: Trying Swagger api documenting tool
  title: Documenting Api
  version: "2.5"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Log in to the application
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Login
  /logout:
    post:
      description: Log out from the application
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Logout
  /signup:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Signup
swagger: "2.0"
